### ISSUE TITLE
Roadmap 0.1.0

### ISSUE THREAD

**Issue by j12y** [PredixDev/predixpy#9]
Planned for next minor release 0.1.0

- [x] Better UAA user support and auth flows
- [x] Encryption of configuration settings
- [x] Documentation and getting started guides
- [x] Python 3.x.x and 2.7.x support

**Comment by Adeel-Abdullah** [comment]
When can we expect release of version 0.1.0?

**Comment by j12y** [comment]
I don't want to commit to a release date, but I'm actively working on these priority items.  My best estimate is 2-5 weeks out depending on other competing priorities during that time frame.  Since Python 3.x is a high value addition it is also possible that may trigger an earlier release.

**Comment by Adeel-Abdullah** [comment]
We're really looking forward to release of the new version as we'd love to use it in our solutions. Keep up the awesome work!

**Comment by msugano** [comment]
Has the version 0.1.0 been already released?

**Comment by j12y** [comment]
Unfortunately it has not.  It is going through some final gatechecks though so a release is imminent.  If you watch this issue it'll be closed once integration merged, release is tagged, and uploaded to PyPI.

**Comment by j12y** [comment]
Should be available with `pip install predix==1.0.0rc1` which will be the next release.
